/* Replace with your SQL commands */

/* Tables */
CREATE TABLE PEOPLE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    WEIGHT FLOAT,
    HEIGHT INTEGER,
    BIRTH_DATE DATE,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);